name: ScrapeJobs

on:
  schedule:
    - cron: '*/1 * * * *'
  workflow_dispatch:

jobs:
  build-and-start:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all tags and branches
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun install
      - run: bun ./index.ts
      - name: Commit and push if changes
        run: |
          git config --global user.email "mhimanshu.338@gmail.com"
          git config --global user.name "Himanshu"
          git add data/jobs.json
          git commit -m "Update jobs data" || echo "No changes to commit"
          git push
