name: ScrapeJobs

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build-and-start:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install
      - run: bun ./index.ts
      - name: Commit and push if changes
        run: |
          git config --global user.email "mhimanshu.338@gmail.com"
          git config --global user.name "Himanshu"
          git add .
          git commit -m "Update jobs data" || echo "No changes to commit"
          git push
